[package]
name = "midi-step"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winrt = "0.8.0"
midir = {version = "0.7.0", features = ["winrt"]}
midi-control = "0.2.0"
rodio="0.15.0"